// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB5XbVP4sFckJ4FpeiJepIsUvKLLLIX5AY',
    appId: '1:944484349845:web:cd1835a534de3baf5b289c',
    messagingSenderId: '944484349845',
    projectId: 'chat-app-39924',
    authDomain: 'chat-app-39924.firebaseapp.com',
    storageBucket: 'chat-app-39924.firebasestorage.app',
    measurementId: 'G-L1TPPH8YQL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBJwaAeSfUkD9BfVhcWyNcgjMkOOGXjWsw',
    appId: '1:944484349845:android:9d86435a2f2e9c765b289c',
    messagingSenderId: '944484349845',
    projectId: 'chat-app-39924',
    storageBucket: 'chat-app-39924.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBlwTKosq5wHH7ZA5mwe_N0NW4iu2ydcLA',
    appId: '1:944484349845:ios:d537422c1ce6e5965b289c',
    messagingSenderId: '944484349845',
    projectId: 'chat-app-39924',
    storageBucket: 'chat-app-39924.firebasestorage.app',
    iosBundleId: 'com.example.appChat',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB5XbVP4sFckJ4FpeiJepIsUvKLLLIX5AY',
    appId: '1:944484349845:web:11f52ac8c36e7f305b289c',
    messagingSenderId: '944484349845',
    projectId: 'chat-app-39924',
    authDomain: 'chat-app-39924.firebaseapp.com',
    storageBucket: 'chat-app-39924.firebasestorage.app',
    measurementId: 'G-QN2B69NKDR',
  );
}
